### ISSUE TITLE
Add `yarn.lock` check

### ISSUE THREAD

**Issue by sdiricco** [primary-color/aicslucca-website#11]
Add following check to github action

```yml
name: Check Yarn Lock File in order to prevent using yarn

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check-yarn-lock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for Yarn Lock File
        run: |
          if [ -f "yarn.lock" ]; then
            echo "Error: Yarn lock file (yarn.lock) detected. Please remove it from your repository."
            exit 1
          else
            echo "No yarn lock file found. Good to go!"
          fi

```
